name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      JWT_SECRET: testsecret   # or use ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'      # match your project
          bundler-cache: true

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Prepare DB (SQLite)
        run: bin/rails db:prepare

      - name: Run tests (RSpec)
        run: bundle exec rspec
        # If you use Minitest instead:
        # run: bundle exec rails test